services:
  mod-loader:
    build:
      context: .
      dockerfile: Dockerfile.slim
    image: "firstwhack/barotrauma-server:slim"
    volumes:
      - "baro-gamedir:/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server"
    environment:
      - GAMEDIR=/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server
    # command: tail -f /dev/null
    command: >
      /bin/sh -c "
      echo \"GAMEDIR is $$GAMEDIR\";
      if [ -f \"$${GAMEDIR}/config_player.xml\" ]; then
        ids=$(grep -oE 'WorkshopMods/Installed/[0-9]+' \"$${GAMEDIR}/config_player.xml\" | grep -oE '[0-9]+' | sort -u);
        echo \"Found workshop IDs: $$ids\";
        for id in $$ids; do
          echo \"Downloading workshop item $$id\";
          steamcmd +login anonymous +workshop_download_item 602960 $$id +quit;
          dest_dir=\"$${GAMEDIR}/WorkshopMods/Installed/$$id\";
          mkdir -p \"$${dest_dir}\";
          cp -r /root/Steam/steamapps/workshop/content/602960/$$id/* \"$${dest_dir}/\" || true;
        done;
        echo \"Mod download complete, updating config_player.xml paths\";
        sed -i 's|C:/Users[^\"]*Installed/|WorkshopMods/Installed/|g' \"$${GAMEDIR}/config_player.xml\";
      fi;
      echo \"Mod-loader task complete, exiting.\";
      exit 0;
      "
  barotrauma-dedicated-server:
    container_name: barotrauma-server-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
    image: "firstwhack/barotrauma-server:slim"
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
    volumes:
      - "baro-gamedir:/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server"
    depends_on:
      mod-loader:
        condition: service_completed_successfully
volumes:
  baro-gamedir: