services:
  mod-loader:
    build:
      context: .
      dockerfile: Dockerfile.slim
    image: "firstwhack/barotrauma-server:slim"
    volumes:
      - "baro-gamedir:/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server"
    environment:
      - GAMEDIR="/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server"
    command: >
      /bin/sh -c "
      if [ -f \"${GAMEDIR}/config_player.xml\" ]; then
        ids=$(grep -oE 'WorkshopMods/Installed/[0-9]+' \"${GAMEDIR}/config_player.xml\" | grep -oE '[0-9]+' | sort -u);
        echo \"Found workshop IDs: $ids\";
        for id in $ids; do
          echo \"Downloading workshop item $id\";
          steamcmd +login anonymous +workshop_download_item 602960 $id +quit;
          mkdir -p \"${GAMEDIR}/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/$id\";
          cp -r /home/runner/Steam/steamapps/workshop/content/602960/$id/* \
                \"${GAMEDIR}/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/$id/\" || true;
        done;
        sed -i 's|C:/Users[^\"]*Installed/|WorkshopMods/Installed/|g' \"${GAMEDIR}/config_player.xml\";
      fi
      "

  barotrauma-dedicated-server:
    container_name: barotrauma-server-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
    image: "firstwhack/barotrauma-server:slim"
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
    volumes:
      - "baro-gamedir:/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server"
    depends_on:
      - mod-loader

volumes:
  baro-gamedir: