name: Publish 'slim' tag to Docker Hub

on:
  schedule:
    # Run on every Wednesday 00:00 UTC
    - cron: '00 0 * * 3'
  push:
    # Run on every push to main branch
    branches: [ main ]

jobs:

  publish-all:

    runs-on: ubuntu-latest
    environment: Publish to Docker Hub

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images (slim)
      run: docker build . --file Dockerfile.slim --tag yanwk/barotrauma-server:slim --tag yanwk/barotrauma-server:slim-$(date +%Y%m%d)
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
    - name: Push to Docker Hub
      run: docker push yanwk/barotrauma-server --all-tags
