name: Publish 'preload' tag to Docker Hub

on:
  schedule:
    # Run everyday at 00:00 UTC
    - cron: '0 0 * * *'
  push:
    # Run on every push to main branch
    branches: [ main ]

jobs:

  publish-all:

    runs-on: ubuntu-latest
    environment: Publish to Docker Hub

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images (preload)
      run: docker build . --file Dockerfile.preload --tag yanwk/barotrauma-server:preload
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
    - name: Push to Docker Hub
      run: docker push yanwk/barotrauma-server --all-tags
