name: Publish 'dockerful' tag to Docker Hub

on:
  schedule:
    # Run every 3 hours
    - cron: '00 */3 * * *'
  push:
    # Run on every push to main branch
    branches: [ main ]

jobs:

  publish-all:

    runs-on: ubuntu-latest
    environment: Publish to Docker Hub

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images (dockerful)
      run: docker build . --file Dockerfile.dockerful --tag yanwk/barotrauma-server:dockerful
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
    - name: Push to Docker Hub
      run: docker push yanwk/barotrauma-server --all-tags
