name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (latest)
      run: docker build . --file Dockerfile --tag yanwk/barotrauma-server:$(date +%y%m%d) --tag yanwk/barotrauma-server:latest

  build-preload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (preload)
      run: docker build . --file Dockerfile.preload --tag yanwk/barotrauma-server:$(date +%y%m%d)-preload --tag yanwk/barotrauma-server:preload
