name: Publish 'dockerful' to Docker Hub

on:
  schedule:
    # # Run on every Friday 00:00 UTC
    - cron: '00 0 * * 5'

jobs:

  build-publish:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v2
      - 
        name: Build 'dockerful'
        id: build-image-dockerful
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          context: .
          containerfiles: Dockerfile.dockerful
          image: yanwk/barotrauma-server
          tags: dockerful
      - 
        name: Push to Docker Hub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with: 
          image: yanwk/barotrauma-server
          tags: ${{ steps.build-image-dockerful.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - 
        name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-dockerhub.outputs.registry-paths }}"
